In [1]:
from google.colab import files
import numpy as np
import pandas as pd

In [2]:
files.upload()

Saving loan_raw_data.csv to loan_raw_data.csv


{'loan_raw_data.csv': b'age,income,home_ownership,emp_length,loan_intent,loan_grade,loan_amount,interest_rate,status,loan_percent_income,default_on_file,cred_hist_length\n22,59000,RENT,123.0,PERSONAL,D,35000,16.02,1,0.59,Y,3\n21,9600,OWN,5.0,EDUCATION,B,1000,11.14,0,0.1,N,2\n25,9600,MORTGAGE,1.0,MEDICAL,C,5500,12.87,1,0.57,N,3\n23,65500,RENT,4.0,MEDICAL,C,35000,15.23,1,0.53,N,2\n24,54400,RENT,8.0,MEDICAL,C,35000,14.27,1,0.55,Y,4\n21,9900,OWN,2.0,VENTURE,A,2500,7.14,1,0.25,N,2\n26,77100,RENT,8.0,EDUCATION,B,35000,12.42,1,0.45,N,3\n24,78956,RENT,5.0,MEDICAL,B,35000,11.11,1,0.44,N,4\n24,83000,RENT,8.0,PERSONAL,A,35000,8.9,1,0.42,N,2\n21,10000,OWN,6.0,VENTURE,D,1600,14.74,1,0.16,N,3\n22,85000,RENT,6.0,VENTURE,B,35000,10.37,1,0.41,N,4\n21,10000,OWN,2.0,HOMEIMPROVEMENT,A,4500,8.63,1,0.45,N,2\n23,95000,RENT,2.0,VENTURE,A,35000,7.9,1,0.37,N,2\n26,108160,RENT,4.0,EDUCATION,E,35000,18.39,1,0.32,N,4\n23,115000,RENT,2.0,EDUCATION,A,35000,7.9,0,0.3,N,4\n23,500000,MORTGAGE,7.0,DEBTCONSOLIDATION,B,30

In [120]:
df=pd.read_csv('loan_raw_data.csv')
df.head()

age  income home_ownership  emp_length loan_intent loan_grade  loan_amount  \
0   22   59000           RENT       123.0    PERSONAL          D        35000   
1   21    9600            OWN         5.0   EDUCATION          B         1000   
2   25    9600       MORTGAGE         1.0     MEDICAL          C         5500   
3   23   65500           RENT         4.0     MEDICAL          C        35000   
4   24   54400           RENT         8.0     MEDICAL          C        35000   

   interest_rate  status  loan_percent_income default_on_file  \
0          16.02       1                 0.59               Y   
1          11.14       0                 0.10               N   
2          12.87       1                 0.57               N   
3          15.23       1                 0.53               N   
4          14.27       1                 0.55               Y   

   cred_hist_length  
0                 3  
1                 2  
2                 3  
3                 2  
4                 4

In [121]:
data=df.to_numpy()
data

array([[22, 59000, 'RENT', ..., 0.59, 'Y', 3],
       [21, 9600, 'OWN', ..., 0.1, 'N', 2],
       [25, 9600, 'MORTGAGE', ..., 0.57, 'N', 3],
       ...,
       [65, 76000, 'RENT', ..., 0.46, 'N', 28],
       [56, 150000, 'MORTGAGE', ..., 0.1, 'N', 26],
       [66, 42000, 'RENT', ..., 0.15, 'N', 30]], dtype=object)

In [122]:
data.shape

(32581, 12)

In [123]:
age=data[:,0].astype(float)
income=data[:,1].astype(float)
ownership=data[:,2]
emp=data[:,3].astype(float)
intent=data[:,4]
grade=data[:,5]
amount=data[:,6].astype(float)
intrest=data[:,7].astype(float)
status=data[:,8].astype(float)
percent=data[:,9].astype(float)
default=data[:,10]
history=data[:,11].astype(float)



#missing values


In [124]:
age_missing=np.isnan(age).sum()
print("age has no. of missing values:",age_missing)
income_missing=np.isnan(income).sum()
print("income has no. of missing values:",income_missing)
ownership_missing = pd.isna(ownership).sum()
print("ownership has no. of missing values:",ownership_missing)
emp_missing=np.isnan(emp).sum()
print("emp has no. of missing values:",emp_missing)
intent_missing=pd.isna(intent).sum()
print("intent has no. of missing values:",intent_missing)
grade_missing=pd.isna(grade).sum()
print("grade has no. of missing values:",grade_missing)
amount_missing=np.isnan(amount).sum()
print("amount has no. of missing values:",amount_missing)
intrest_missing=np.isnan(intrest).sum()
print("intrest has no. of missing values:",intrest_missing)
status_missing=np.isnan(status).sum()
print("status has no. of missing values:",status_missing)
percent_missing=np.isnan(percent).sum()
print("percent has no. of missing values:",percent_missing)
default_missing=pd.isna(default).sum()
print("default has no. of missing values:",default_missing)
history_missing=np.isnan(history).sum()
print('history has no. of missing values:',history_missing)

age has no. of missing values: 0
income has no. of missing values: 0
ownership has no. of missing values: 0
emp has no. of missing values: 895
intent has no. of missing values: 0
grade has no. of missing values: 0
amount has no. of missing values: 0
intrest has no. of missing values: 3116
status has no. of missing values: 0
percent has no. of missing values: 0
default has no. of missing values: 0
history has no. of missing values: 0


#**1. FIXING MISSING VALUES**

##-- emp column

In [125]:
print(f'the total missing values in emp are {np.isnan(emp).sum()}')
#we are going to replace it with median values because median has no affect on most outlying values
median_emp=np.nanmedian(emp)
print(f"median value of emp is {median_emp}")

missing_emp=np.where(np.isnan(emp))[0]
print("missing emp:",missing_emp)
emp[missing_emp]=median_emp
emp

the total missing values in emp are 895
median value of emp is 4.0
missing emp: [  105   222   379   407   408   433   443   529   567   691   740   741
   744   745   773   829   845   868   876   878   881   882   884   889
   897   916   950   954   965   986  1081  1095  1131  1143  1147  1260
  1326  1352  1379  1388  1395  1408  1420  1433  1437  1438  1451  1462
  1468  1483  1520  1529  1538  1542  1557  1592  1627  1647  1651  1654
  1655  1677  1681  1684  1698  1701  1707  1711  1733  1760  1767  1793
  1802  1810  1812  1921  1929  1943  1960  1969  1975  1991  1998  2007
  2030  2054  2063  2071  2079  2080  2095  2164  2171  2172  2219  2221
  2237  2280  2287  2314  2317  2321  2324  2333  2374  2387  2449  2451
  2487  2490  2554  2563  2615  2651  2658  2660  2696  2702  2774  2814
  2897  2943  2946  2953  2966  2967  3002  3006  3098  3120  3127  3139
  3167  3178  3185  3186  3229  3264  3265  3266  3281  3319  3349  3359
  3365  3448  3451  3452  3456  3461  3487  

array([123.,   5.,   1., ...,   3.,   5.,   2.])

In [126]:
print(f'the total missing values in emp are {np.isnan(emp).sum()}')
print(f'the max value in emp are {np.max(emp)}')

the total missing values in emp are 0
the max value in emp are 123.0


##--intrest column

In [127]:
print(f'the total missing values in intrest are {np.isnan(intrest).sum()}')
#we are going to replace it with median values because median has no affect on most outlying values
median_intrest=np.nanmedian(intrest)
print(f"median value of intrest is {median_intrest}")

missing_intrest=np.where(np.isnan(intrest))[0]
print("missing intrest:",missing_intrest)
intrest[missing_intrest]=median_intrest
intrest

the total missing values in intrest are 3116
median value of intrest is 10.99
missing intrest: [   39    50    57 ... 32553 32569 32570]


array([16.02, 11.14, 12.87, ..., 10.99, 11.48,  9.99])

In [128]:
print(f'the total missing values in intrest are {np.isnan(intrest).sum()}')
print(f'the max value in intrest are {np.max(intrest)}')

the total missing values in intrest are 0
the max value in intrest are 23.22


----------------------------------------------------------------------------------------------------------------------------------------------------------------

# **2) FIXING OUTLIERS**

In [129]:
def outliers(column):
  q1=np.percentile(column,25)
  q3=np.percentile(column,75)

  iqr=q3-q1
  lower=q1-(iqr*1.5)
  upper=q3+(iqr*1.5)

  outliers=np.where((column<lower)|(column>upper))[0]
  print("lower:",lower)
  print("upper:",upper)
  return outliers
def lower(column):
  q1=np.percentile(column,25)
  q3=np.percentile(column,75)

  iqr=q3-q1
  lower=q1-(iqr*1.5)
  return lower
def upper(column):
  q1=np.percentile(column,25)
  q3=np.percentile(column,75)

  iqr=q3-q1
  upper=q3+(iqr*1.5)
  return upper

###clean data for age

In [130]:
print("outliers in age(index):",outliers(age))

lower: 12.5
upper: 40.5
outliers in age(index): [   81   183   575 ... 32578 32579 32580]


In [131]:
#but the age limit of giving loan is between 18 and 70
out_age=np.where((age<18)|(age>70))[0]
print("Outlier count:", out_age.shape)
print("Outlier age:", age[out_age])

#now valid ages
valid_age = age[(age >= 18) & (age <= 70)]

#median on ages
median = np.median(valid_age)
print("median of ages is:",median)
# replace invalid ages
age[out_age]=median
age

Outlier count: (13,)
Outlier age: [144. 144. 123. 123. 144.  78.  73.  94.  80.  73.  84.  73.  76.]
median of ages is: 26.0


array([22., 21., 25., ..., 65., 56., 66.])

###clean data for income

In [132]:
outliers(income)
print(f"max income is {np.max(income)}")
print(f"the 99th percentile of income is {np.round(np.percentile(income,99))}")
print(f"count if income above 99th percentile {np.sum(income>225200)}")

lower: -22550.0
upper: 140250.0
max income is 6000000.0
the 99th percentile of income is 225200.0
count if income above 99th percentile 326


In [133]:
#so we have 99th percentile as 225200 and max income as 6000000 which can be a potential outlier but the count is low so we can replace or cap it with nearest percentile value
out_income = np.where((income < 1000) | (income > 225200))[0]
print("Outlier count:", out_income.shape)
print("Outlier income(inr):", income[np.where(income>225200)][:10])

# get valid income values
valid_income = income[(income >= 1000) & (income <= 225200)]

# correct income
correct_income = 225200
print("99th percent corrected income:", correct_income)

# replace outliers with median
income = np.where((income < 1000) | (income > 225200), correct_income, income)
income


Outlier count: (326,)
Outlier income(inr): [500000. 306000. 300000. 300000. 300000. 300000. 300000. 300000. 280000.
 277104.]
99th percent corrected income: 225200


array([ 59000.,   9600.,   9600., ...,  76000., 150000.,  42000.])

In [134]:
print(f"count if income above 99th percentile is {np.sum(income>225200)}")

count if income above 99th percentile is 0


###clean data for amount

In [135]:
print("minimum loan amount:",amount.min())
print("maximum loan amount:",amount.max())
#hence we don't need to clean the amount data as no outlier detcted and no missing values found

minimum loan amount: 500.0
maximum loan amount: 35000.0


###cleaning data for intrest

In [136]:
#find the min and max interest offered
print("minimum intrest:",np.nanmin(intrest))
print("maximum intrest:",np.nanmax(intrest))

#so all the values are between this only so we are not considering outliers

minimum intrest: 5.42
maximum intrest: 23.22


###cleaning data for history

In [ ]:
n=np.where(history>20)[0]
n.size
#we don't need to convert these outliers because some may have long credit history

213

#3) CORRECT PERCENTAGE


In [143]:
percent=amount/income
np.round(percent,2)

array([0.59, 0.1 , 0.57, ..., 0.46, 0.1 , 0.15])

#EXPORTING TABLE

In [144]:
cleaned_data = np.column_stack([age,income,ownership,emp,intent,grade,amount,intrest,status,percent,default,history])

In [145]:
cleaned_data

array([[22.0, 59000.0, 'RENT', ..., 0.5932203389830508, 'Y', 3.0],
       [21.0, 9600.0, 'OWN', ..., 0.10416666666666667, 'N', 2.0],
       [25.0, 9600.0, 'MORTGAGE', ..., 0.5729166666666666, 'N', 3.0],
       ...,
       [65.0, 76000.0, 'RENT', ..., 0.4605263157894737, 'N', 28.0],
       [56.0, 150000.0, 'MORTGAGE', ..., 0.1, 'N', 26.0],
       [66.0, 42000.0, 'RENT', ..., 0.15416666666666667, 'N', 30.0]],
      dtype=object)

In [146]:
cleaned_data=pd.DataFrame(cleaned_data)
cleaned_data.to_csv("cleaned_numpy_data.csv",index=False)
files.download("cleaned_numpy_data.csv")

<IPython.core.display.Javascript object>

<IPython.core.display.Javascript object>